
# Anti-Bot Configuration for Homes.com Testing
# 10 different strategies to bypass blocking

strategies:
  1:
    name: "Basic Chrome Desktop"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
    viewport: [1920, 1080]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      DNT: "1"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    stealth: true
    delay: 3

  2:
    name: "Firefox Desktop with Extensions"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
    viewport: [1366, 768]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate, br"
      DNT: "1"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
      Sec-Fetch-Dest: "document"
      Sec-Fetch-Mode: "navigate"
      Sec-Fetch-Site: "none"
    stealth: true
    delay: 5

  3:
    name: "Mobile Chrome Android"
    user_agent: "Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36"
    viewport: [375, 667]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
      Sec-Fetch-Dest: "document"
      Sec-Fetch-Mode: "navigate"
      Sec-Fetch-Site: "none"
      Sec-Fetch-User: "?1"
    mobile: true
    stealth: true
    delay: 4

  4:
    name: "Safari macOS"
    user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
    viewport: [1440, 900]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    stealth: true
    delay: 6

  5:
    name: "Edge Windows with Residential Headers"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
    viewport: [1536, 864]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Cache-Control: "max-age=0"
      Connection: "keep-alive"
      DNT: "1"
      Upgrade-Insecure-Requests: "1"
      Sec-Ch-Ua: '"Chromium";v="118", "Microsoft Edge";v="118", "Not=A?Brand";v="99"'
      Sec-Ch-Ua-Mobile: "?0"
      Sec-Ch-Ua-Platform: '"Windows"'
      Sec-Fetch-Dest: "document"
      Sec-Fetch-Mode: "navigate"
      Sec-Fetch-Site: "none"
      Sec-Fetch-User: "?1"
    stealth: true
    delay: 7

  6:
    name: "Chrome with Fake WebRTC"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
    viewport: [1280, 720]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9,es;q=0.8"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    stealth: true
    webrtc_fake: true
    delay: 8

  7:
    name: "Firefox Mobile iOS"
    user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/119.0 Mobile/15E148 Safari/605.1.15"
    viewport: [414, 896]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    mobile: true
    stealth: true
    delay: 9

  8:
    name: "Chrome with Custom TLS"
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
    viewport: [1920, 1200]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
      X-Forwarded-For: "192.168.1.100"
      X-Real-IP: "192.168.1.100"
    stealth: true
    delay: 10

  9:
    name: "Slow Human-like Chrome"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
    viewport: [1600, 900]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    stealth: true
    human_timing: true
    delay: 15

  10:
    name: "Tor-like Firefox"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/119.0"
    viewport: [1024, 768]
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
    stealth: true
    tor_like: true
    delay: 12
